=== Iker-99/Playlist/Playlist.dtd
SYSTEM
<?xml version="1.0" encoding="UTF-8"?>
    <!ELEMENT Canciones_mas_escuchadas (orden)+>
        <!ELEMENT orden (canciones, cantante)+>

            <!ELEMENT canciones (nombrec, visitas, comentarios*, dinero_generado)+>
            <!ATTLIST canciones favorita (Si|No) #REQUIRED>
            <!ELEMENT nombrec (#PCDATA)>
            <!ELEMENT visitas (#PCDATA)>
            <!ELEMENT comentarios (#PCDATA)>
            <!ELEMENT dinero_generado (#PCDATA)>

            <!ELEMENT cantante (nombre, edad, discos, premios? )>
            <!ATTLIST cantante genero (Pop|Rock|Jazz|Blues|Rock_transgresivo|Rumba) #REQUIRED>
            <!ATTLIST cantante imagen #PCDATA>
            <!ATTLIST cantante top_ventas ID #REQUIRED>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT edad (#PCDATA)>
            <!ELEMENT discos (#PCDATA)>
            <!ELEMENT premios (#PCDATA)>

=== Iker-99/Playlist/Playlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Canciones_mas_escuchadas SYSTEM "Projecte/Playlist.dtd">

<Canciones_mas_escuchadas>
   <orden>
       <canciones favorita="Si">
           <nombrec> Caminando Por La Vida</nombrec>
           <visitas>37 Millones</visitas>
           <comentarios>Una cancion muy buena relajante pero divertida</comentarios>
           <dinero_generado>40,000€</dinero_generado>
       </canciones>
       <cantante genero="Pop" top_ventas="2" imagen="Imagenes/Melendi.png">
           <nombre>Melendi</nombre>
           <edad>45</edad>
           <discos>12</discos>
       </cantante>
   </orden>
    <orden>
        <canciones favorita="Si">
            <nombrec> Tango suicida</nombrec>
            <visitas>12 Millones</visitas>
            <comentarios>Me a tocado el corazon es muy bonita</comentarios>
            <dinero_generado>22,000€</dinero_generado>
        </canciones>
        <cantante genero="Rock_transgresivo" top_ventas="3" imagen="Imagenes/Robe.jpg">
            <nombre>Extremoduro</nombre>
            <edad>62</edad>
            <discos>12</discos>
        </cantante>
    </orden>
    <orden>
        <canciones favorita="No">
            <nombrec>Vino tinto</nombrec>
            <visitas>70 Millones</visitas>
            <dinero_generado>76,000€</dinero_generado>
        </canciones>
        <cantante genero="Rumba" top_ventas="1" imagen="Imagenes/Estopa.png">
            <nombre>Estopa</nombre>
            <edad>45</edad>
            <discos>11</discos>
        </cantante>
    </orden>
    <orden>
        <canciones favorita="No">
            <nombrec>Trozos De Cristal</nombrec>
            <visitas>2,6 Millones</visitas>
            <comentarios>Muy entretenida</comentarios>
            <comentarios>La version de fito solo es la mejor</comentarios>
            <dinero_generado>3,600€</dinero_generado>
        </canciones>
        <cantante genero="Rock" top_ventas="4" imagen="Imagenes/Fito.png">
            <nombre>Fito</nombre>
            <edad>58</edad>
            <discos>7</discos>
        </cantante>
    </orden>
    <orden>
        <canciones favorita="Si">
            <nombrec> La Canción Más Hermosa del Mundo</nombrec>
            <visitas>1,5 Millones</visitas>
            <comentarios>Sin palabras</comentarios>
            <dinero_generado>1,500€</dinero_generado>
        </canciones>
        <cantante genero="Pop" top_ventas="5" imagen="Imagenes/Joaquin.png">
            <nombre>Joaquin sabina</nombre>
            <edad>75</edad>
            <discos>18</discos>
        </cantante>
    </orden>
</Canciones_mas_escuchadas>

=== Iker-99/Playlist/ProjecteT1-P1-IFI.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Canciones_mas_escuchadas SYSTEM "Projecte/Playlist.dtd">

<Canciones_mas_escuchadas>
   <orden>
       <canciones favorita="Si">
           <nombrec> Caminando Por La Vida</nombrec>
           <visitas>37 Millones</visitas>
           <comentarios>Una cancion muy buena relajante pero divertida</comentarios>
           <dinero_generado>40,000€</dinero_generado>
       </canciones>
       <cantante genero="Pop" top_ventas="t2" imagen="Imagenes/Melendi.png">
           <nombre>Melendi</nombre>
           <edad>45</edad>
           <discos>12</discos>
           <premios>2 discos de oro y 9 discos platino</premios>
       </cantante>
   </orden>
    <orden>
        <canciones favorita="Si">
            <nombrec> Tango suicida</nombrec>
            <visitas>12 Millones</visitas>
            <comentarios>Me a tocado el corazon es muy bonita</comentarios>
            <dinero_generado>22,000€</dinero_generado>
        </canciones>
        <cantante genero="Rock_transgresivo" top_ventas="t3" imagen="Imagenes/Robe.jpg">
            <nombre>Extremoduro</nombre>
            <edad>62</edad>
            <discos>12</discos>
            <premios>3 disco de oro y 5 de platino</premios>
        </cantante>
    </orden>
    <orden>
        <canciones favorita="No">
            <nombrec>Vino tinto</nombrec>
            <visitas>70 Millones</visitas>
            <dinero_generado>76,000€</dinero_generado>
        </canciones>
        <cantante genero="Rumba" top_ventas="t1" imagen="Imagenes/Estopa.png">
            <nombre>Estopa</nombre>
            <edad>45</edad>
            <discos>11</discos>
            <premios>4 discos de oro y 7 de platino</premios>
        </cantante>
    </orden>
    <orden>
        <canciones favorita="No">
            <nombrec>Trozos De Cristal</nombrec>
            <visitas>2,6 Millones</visitas>
            <comentarios>Muy entretenida</comentarios>
            <comentarios>La version de fito solo es la mejor</comentarios>
            <dinero_generado>3,600€</dinero_generado>
        </canciones>
        <cantante genero="Rock" top_ventas="t4" imagen="Imagenes/Fito.png">
            <nombre>Fito</nombre>
            <edad>58</edad>
            <discos>7</discos>
            <premios>3 discos de oro y 5 de platino</premios>
        </cantante>
    </orden>
    <orden>
        <canciones favorita="Si">
            <nombrec> La Canción Más Hermosa del Mundo</nombrec>
            <visitas>1,5 Millones</visitas>
            <comentarios>Sin palabras</comentarios>
            <dinero_generado>1,500€</dinero_generado>
        </canciones>
        <cantante genero="Pop" top_ventas="t5" imagen="Imagenes/Joaquin.png">
            <nombre>Joaquin sabina</nombre>
            <edad>75</edad>
            <discos>18</discos>
            <premios>5 discos de oro y 3 de platino</premios>
        </cantante>
    </orden>
</Canciones_mas_escuchadas>
